[package]
name = "lupt"
version = "0.2.0"
description = "Chat app for lupt(लुप्त) users!"
authors = ["Piyush Raj <piyush.raj.kit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-web = { version = "3", features = ["openssl"] }
actix-web-actors = "3"
actix-broker = "0.3.1"
actix-files = "0.5.0"
actix-ratelimit = "0.3.1"
env_logger = "0.8.3"
openssl = "0.10.28"

dotenv = "0.15.0"
clap = "2.33.3"
lazy_static = "1.4.0"

serde = "1.0.123"
serde_json = "1.0.62"
rand = "0.8.3"
futures = "0.3.12"

sha1 = "0.6.0"
base64 = "0.13.0"
