# This is called from ./test_buildpack.
version: "2"
services:
  testbuild:
    image: "heroku/cedar"
    volumes:
      - ".:/src"
    working_dir: "/src"
    environment:
      HOME: "/src"
    user: "$UID:$GROUPS"
    command: ["bin/compile", "/src/rust-buildpack-example-actix", "/src/cache"]
