
version: "3.2"
services:
  web:
    image: "ghcr.io/piyushxcoder/lupt:main"
    restart: always
    ports:
      - ${PORT}:8000
    volumes:
      - ${CONFIG}:/app/config.json
      - ${LOG}:/app/logs.txt:rw
    environment:
      - RUST_LOG=actix_web=info
