
version: "3.2"
services:
  web:
    build:
      context: .
      args:
        RUNNER_USER_ID: 1000
        RUNNER_GROUP_ID: 1000
    ports:
      - ${PORT}:8000
    volumes:
      - ${CONFIG}:/app/config.json
      - ${LOG}:/app/logs.txt:rw
    environment:
      - RUST_LOG=actix_web=info


