name: Docker Image CI

on:
  push:
    branches: 
      - "main"

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker buildx create --name builder1 --use --bootstrap
              docker buildx build --push --platform linux/arm64/v8,linux/amd64 \
                --build-arg="RUNNER_GROUP_ID=${{vars.RUNNER_GROUP_ID}}" \
                --build-arg="RUNNER_USER_ID=${{vars.RUNNER_USER_ID}}" \
                --build-arg="APP=${{vars.APP}}" --tag ghcr.io/${GITHUB_REPOSITORY,,}:main $(pwd)

