name: Docker Image CI

on:
  push:
    branches: 
      - "main"
      - "PiyushXCoder-workflow"
  # pull_request:
  #   branches: 
  #     - "main"

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
          
          - name: 'List'
            run: ls

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/${GITHUB_REPOSITORY,,}:main
              docker push ghcr.io/${GITHUB_REPOSITORY,,}:main

