name: Docker Image CI

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/${{github.repository,,}}:main
              docker push ghcr.io/${{github.repository,,}}:main

