name: Docker Image CI

on:
  push:
    branches: 
      - "main"
      - "PiyushXCoder-workflow"

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              echo docker buildx build --load --platform linux/arm64 --build-arg="RUNNER_GROUP_ID=${RUNNER_GROUP_ID}" --build-arg="RUNNER_USER_ID=${RUNNER_USER_ID}" --build-arg="APP=${APP}" -t --tag ghcr.io/${GITHUB_REPOSITORY,,}:main .
              # docker push ghcr.io/${GITHUB_REPOSITORY,,}:main

